#pragma once
/*
 * tn.h - token type
 * progrmmer 백지수, 송주은, 정연우
 * date - 05/04/2020
 */
enum token { TEOF, TCONST, TELSE, TIF, TINT, TRETURN, TVOID, TWHILE, TPLUS, TMINUS, TSTAR, TSLASH, TMOD,
			 TASSIGN, TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN, TNOT, TAND, TOR,
			 TEQUAL, TNOTEQU, TLESS, TGREAT, TLESSE, TGREATE, TINC, TDEC, TIDENT, TNUMBER, TRNUMBER, TCOMMA, TSEMI,
			 TBROPEN, TBRCLOSE, TCURLOPEN, TCURLCLOSE, TSQUOPEN, TSQUCLOSE, TILLICHAR, TILLIDENT };